name: github-pages

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest

      - uses: actions/cache@v2
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}

      - name: Build website
        run: hugo --minify

      - name: Upload static bundle
        uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: public

  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Download static bundle
        uses: actions/download-artifact@v2
        with:
          name: bundle
          path: public

      - name: Configure documentation domain
        run: echo $DOMAIN > public/CNAME
        env:
          DOMAIN: ${{ secrets.DOMAIN }}

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: github-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
